### ISSUE TITLE
Brightcove --> Error: Unexpected data from AMF gateway

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MiraculousLegendas/get-flash-videos#46]
```
What steps will reproduce the problem?

1. get_flash_videos http://link.brightcove.com/services/player/bcpid713271701?
bclid=713073346&bctid=709364416

What is the expected output? What do you see instead?

It should normally download the video but instead it outputs the following 
error:

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm the site is using Flash video and if you have Flash available
check that the URL really works(!).

Check for updates by running: /usr/bin/get_flash_videos --update

If the latest version does not support this please open a bug (or
contribute a patch!) at http://code.google.com/p/get-flash-videos/
make sure you include the output with --debug enabled.

Version with debug:

get_flash_videos --debug 
http://link.brightcove.com/services/player/bcpid713271701?
bclid=713073346&bctid=709364416
[1] 15444
Macbook-X:~ Karim$ No plugins installed
Downloading 
http://link.brightcove.com/services/player/bcpid713271701?bclid=713073346
-> GET http://link.brightcove.com/services/player/bcpid713271701?bclid=713073346
<- 200 text/html;charset=utf-8 (1696)
Trying to open plugin /Users/Karim/.get_flash_videos/plugins/Link.pm
Using method 'brightcove' for 
http://link.brightcove.com/services/player/bcpid713271701?
bclid=713073346
Extracted playerId: 713271701, video_id: 
$VAR1 = bless( {
                 'messages' => [
                                 bless( {
                                          'source' => 'levelerrordetails    åcom.brightcove.BrightcoveException: An 
error occured processing the request.
    at 
com.brightcove.templating.TemplatingFacade.getContentForTemplateInstance(Templat
ingFacade
.java:117)
    at sun.reflect.GeneratedMethodAccessor834.invoke(Unknown Source)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.openamf.invoker.RankedMethod.invoke(RankedMethod.java:75)
    at 
com.brightcove.container.OpenAmfContainerInvoker.invokeServiceMethod(OpenAmfCont
ainerInv
oker.java:90)
    at 
com.brightcove.container.OpenAmfContainerInvoker.invokeService(OpenAmfContainerI
nvoker.jav
a:60)
    at org.openamf.DefaultGateway.invokeBody(DefaultGateway.java:209)
    at com.brightcove.openamf.BrightcoveGateway.invokeBody(BrightcoveGateway.java:199)
    at com.brightcove.openamf.BrightcoveGateway.processMessage(BrightcoveGateway.java:87)
    at org.openamf.DefaultGateway.service(DefaultGateway.java:96)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:252)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.brightcove.servlet.BrightcoveServletFilter.doFilter(BrightcoveServletFilter.java:46)
    at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
    at 
org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConne
ction(Htt
p11BaseProtocol.java:664)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
    at 
org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorker
Thread.java:
80)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
    at java.lang.Thread.run(Thread.java:619)

description(An error occured processing the 
request.codeSERVER.PROCESSINGtype"com.brightcove.BrightcoveException    ',
                                          'target_uri' => '/2/onStatus',
                                          'version' => 0,
                                          'value' => {
                                                       'level' => 'error',
                                                       'type' => 'com.brightcove.BrightcoveException',
                                                       'description' => 'An error occured processing the request.',
                                                       'details' => 'com.brightcove.BrightcoveException: An error 
occured processing the request.
    at 
com.brightcove.templating.TemplatingFacade.getContentForTemplateInstance(Templat
ingFacade
.java:117)
    at sun.reflect.GeneratedMethodAccessor834.invoke(Unknown Source)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.openamf.invoker.RankedMethod.invoke(RankedMethod.java:75)
    at 
com.brightcove.container.OpenAmfContainerInvoker.invokeServiceMethod(OpenAmfCont
ainerInv
oker.java:90)
    at 
com.brightcove.container.OpenAmfContainerInvoker.invokeService(OpenAmfContainerI
nvoker.jav
a:60)
    at org.openamf.DefaultGateway.invokeBody(DefaultGateway.java:209)
    at com.brightcove.openamf.BrightcoveGateway.invokeBody(BrightcoveGateway.java:199)
    at com.brightcove.openamf.BrightcoveGateway.processMessage(BrightcoveGateway.java:87)
    at org.openamf.DefaultGateway.service(DefaultGateway.java:96)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:252)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.brightcove.servlet.BrightcoveServletFilter.doFilter(BrightcoveServletFilter.java:46)
    at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
    at 
org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConne
ction(Htt
p11BaseProtocol.java:664)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
    at 
org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorker
Thread.java:
80)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
    at java.lang.Thread.run(Thread.java:619)
',
                                                       'code' => 'SERVER.PROCESSING'
                                                     },
                                          'response_uri' => ''
                                        }, 'Data::AMF::Message' )
                               ],
                 'headers' => [],
                 'version' => 0
               }, 'Data::AMF::Packet' );

Error: Unexpected data from AMF gateway at /usr/bin/get_flash_videos line 7817.

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.


What version of the product are you using? On what operating system?

Using latest version 1.17 combined on Mac OS X 10.6.1 / Perl 5.10.1 / And all 
modules up to 
dates !


Please provide any additional information below.

Tried updating all modules, perl.. etc. But didn't do the trick !

A solution would be much appreciated ! Thanks.


```

Original issue reported on code.google.com by `rimkashox` on 5 Nov 2009 at 7:36

**Comment by GoogleCodeExporter** [comment]
```
I just ran into what seems to be the same problem with

http://www.informationweek.com/video/personaltechnology/77209909001

This URL redirects, so redirection needs to be enabled, or the file has to be
downloaded manually and then referenced with a file:// URL.

Part of this seems to be a bug at the brightcove servers, funny that they seem 
to
crash so easily.

```

Original comment by `pw...@pweis.com` on 29 Apr 2010 at 5:08

**Comment by GoogleCodeExporter** [comment]
```
I have similar problems with 
http://www.fox.com/thesimpsons/full-episodes/944150404001/500-keys
```

Original comment by `mjbauer95` on 17 May 2011 at 2:01

**Comment by GoogleCodeExporter** [comment]
```
Issue 78 has been merged into this issue.
```

Original comment by `mjbauer95` on 17 May 2011 at 2:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `mjbauer95` on 8 Aug 2011 at 1:55
- Changed state: **Accepted**
